# Generated by Django 5.1.3 on 2025-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asigapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
