# Generated by Django 5.1.3 on 2025-01-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asigapp', '0004_alter_blogpost_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
